"""updated tables

Revision ID: 370b246581e0
Revises: 325cdcd70ff9
Create Date: 2024-12-09 01:02:41.358934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370b246581e0'
down_revision: Union[str, None] = '325cdcd70ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_breach', sa.Column('records_affected', sa.Integer(), nullable=True))
    op.add_column('data_breach', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('data_breach', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('emails', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('emails', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'updated_at')
    op.drop_column('emails', 'created_at')
    op.drop_column('data_breach', 'updated_at')
    op.drop_column('data_breach', 'created_at')
    op.drop_column('data_breach', 'records_affected')
    # ### end Alembic commands ###
