"""Added domain_ioc table

Revision ID: ac37aec80e7c
Revises: 
Create Date: 2024-11-24 23:08:52.702369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac37aec80e7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_ioc',
    sa.Column('ioc', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('ioc_type', sa.String(), nullable=True),
    sa.Column('geometric_location', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ioc')
    )
    op.create_table('domain_ioc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_address', sa.String(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_ioc')
    op.drop_table('api_ioc')
    # ### end Alembic commands ###
